@echo off
echo Pulling latest code...
git pull
echo Building project...
mvn clean install
echo Switching to examples...
cd examples
echo Starting the test code...
mvn clean compile exec:java -Dexec.mainClass="org.multibit.hd.hardware.examples.trezor.usb.UsbMonitoringExample"
cd ..
