// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeviceDescriptorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 vendor_id = 1;
    /**
     * <code>optional uint32 vendor_id = 1;</code>
     *
     * <pre>
     * USB vendor ID
     * </pre>
     */
    boolean hasVendorId();
    /**
     * <code>optional uint32 vendor_id = 1;</code>
     *
     * <pre>
     * USB vendor ID
     * </pre>
     */
    int getVendorId();

    // optional uint32 product_id = 2;
    /**
     * <code>optional uint32 product_id = 2;</code>
     *
     * <pre>
     * USB product ID
     * </pre>
     */
    boolean hasProductId();
    /**
     * <code>optional uint32 product_id = 2;</code>
     *
     * <pre>
     * USB product ID
     * </pre>
     */
    int getProductId();

    // optional string serial_number = 3;
    /**
     * <code>optional string serial_number = 3;</code>
     *
     * <pre>
     * USB serial number
     * </pre>
     */
    boolean hasSerialNumber();
    /**
     * <code>optional string serial_number = 3;</code>
     *
     * <pre>
     * USB serial number
     * </pre>
     */
    java.lang.String getSerialNumber();
    /**
     * <code>optional string serial_number = 3;</code>
     *
     * <pre>
     * USB serial number
     * </pre>
     */
    com.google.protobuf.ByteString
        getSerialNumberBytes();

    // optional string path = 4;
    /**
     * <code>optional string path = 4;</code>
     *
     * <pre>
     * USB device path
     * </pre>
     */
    boolean hasPath();
    /**
     * <code>optional string path = 4;</code>
     *
     * <pre>
     * USB device path
     * </pre>
     */
    java.lang.String getPath();
    /**
     * <code>optional string path = 4;</code>
     *
     * <pre>
     * USB device path
     * </pre>
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * Protobuf type {@code DeviceDescriptor}
   *
   * <pre>
   **
   * Device Descriptor used in Configuration
   * </pre>
   */
  public static final class DeviceDescriptor extends
      com.google.protobuf.GeneratedMessage
      implements DeviceDescriptorOrBuilder {
    // Use DeviceDescriptor.newBuilder() to construct.
    private DeviceDescriptor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceDescriptor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceDescriptor defaultInstance;
    public static DeviceDescriptor getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceDescriptor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceDescriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              vendorId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              productId_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serialNumber_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              path_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Config.internal_static_DeviceDescriptor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Config.internal_static_DeviceDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Config.DeviceDescriptor.class, Config.DeviceDescriptor.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceDescriptor> PARSER =
        new com.google.protobuf.AbstractParser<DeviceDescriptor>() {
      public DeviceDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceDescriptor(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceDescriptor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 vendor_id = 1;
    public static final int VENDOR_ID_FIELD_NUMBER = 1;
    private int vendorId_;
    /**
     * <code>optional uint32 vendor_id = 1;</code>
     *
     * <pre>
     * USB vendor ID
     * </pre>
     */
    public boolean hasVendorId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 vendor_id = 1;</code>
     *
     * <pre>
     * USB vendor ID
     * </pre>
     */
    public int getVendorId() {
      return vendorId_;
    }

    // optional uint32 product_id = 2;
    public static final int PRODUCT_ID_FIELD_NUMBER = 2;
    private int productId_;
    /**
     * <code>optional uint32 product_id = 2;</code>
     *
     * <pre>
     * USB product ID
     * </pre>
     */
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 product_id = 2;</code>
     *
     * <pre>
     * USB product ID
     * </pre>
     */
    public int getProductId() {
      return productId_;
    }

    // optional string serial_number = 3;
    public static final int SERIAL_NUMBER_FIELD_NUMBER = 3;
    private java.lang.Object serialNumber_;
    /**
     * <code>optional string serial_number = 3;</code>
     *
     * <pre>
     * USB serial number
     * </pre>
     */
    public boolean hasSerialNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string serial_number = 3;</code>
     *
     * <pre>
     * USB serial number
     * </pre>
     */
    public java.lang.String getSerialNumber() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serialNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serial_number = 3;</code>
     *
     * <pre>
     * USB serial number
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSerialNumberBytes() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string path = 4;
    public static final int PATH_FIELD_NUMBER = 4;
    private java.lang.Object path_;
    /**
     * <code>optional string path = 4;</code>
     *
     * <pre>
     * USB device path
     * </pre>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string path = 4;</code>
     *
     * <pre>
     * USB device path
     * </pre>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string path = 4;</code>
     *
     * <pre>
     * USB device path
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      vendorId_ = 0;
      productId_ = 0;
      serialNumber_ = "";
      path_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, vendorId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, productId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSerialNumberBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPathBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, vendorId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, productId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSerialNumberBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPathBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Config.DeviceDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Config.DeviceDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Config.DeviceDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Config.DeviceDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Config.DeviceDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Config.DeviceDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Config.DeviceDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Config.DeviceDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Config.DeviceDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Config.DeviceDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Config.DeviceDescriptor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceDescriptor}
     *
     * <pre>
     **
     * Device Descriptor used in Configuration
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Config.DeviceDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Config.internal_static_DeviceDescriptor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Config.internal_static_DeviceDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Config.DeviceDescriptor.class, Config.DeviceDescriptor.Builder.class);
      }

      // Construct using Config.DeviceDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        vendorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        productId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        serialNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Config.internal_static_DeviceDescriptor_descriptor;
      }

      public Config.DeviceDescriptor getDefaultInstanceForType() {
        return Config.DeviceDescriptor.getDefaultInstance();
      }

      public Config.DeviceDescriptor build() {
        Config.DeviceDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Config.DeviceDescriptor buildPartial() {
        Config.DeviceDescriptor result = new Config.DeviceDescriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.vendorId_ = vendorId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.productId_ = productId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serialNumber_ = serialNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Config.DeviceDescriptor) {
          return mergeFrom((Config.DeviceDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Config.DeviceDescriptor other) {
        if (other == Config.DeviceDescriptor.getDefaultInstance()) return this;
        if (other.hasVendorId()) {
          setVendorId(other.getVendorId());
        }
        if (other.hasProductId()) {
          setProductId(other.getProductId());
        }
        if (other.hasSerialNumber()) {
          bitField0_ |= 0x00000004;
          serialNumber_ = other.serialNumber_;
          onChanged();
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000008;
          path_ = other.path_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Config.DeviceDescriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Config.DeviceDescriptor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 vendor_id = 1;
      private int vendorId_ ;
      /**
       * <code>optional uint32 vendor_id = 1;</code>
       *
       * <pre>
       * USB vendor ID
       * </pre>
       */
      public boolean hasVendorId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 vendor_id = 1;</code>
       *
       * <pre>
       * USB vendor ID
       * </pre>
       */
      public int getVendorId() {
        return vendorId_;
      }
      /**
       * <code>optional uint32 vendor_id = 1;</code>
       *
       * <pre>
       * USB vendor ID
       * </pre>
       */
      public Builder setVendorId(int value) {
        bitField0_ |= 0x00000001;
        vendorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 vendor_id = 1;</code>
       *
       * <pre>
       * USB vendor ID
       * </pre>
       */
      public Builder clearVendorId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        vendorId_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 product_id = 2;
      private int productId_ ;
      /**
       * <code>optional uint32 product_id = 2;</code>
       *
       * <pre>
       * USB product ID
       * </pre>
       */
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 product_id = 2;</code>
       *
       * <pre>
       * USB product ID
       * </pre>
       */
      public int getProductId() {
        return productId_;
      }
      /**
       * <code>optional uint32 product_id = 2;</code>
       *
       * <pre>
       * USB product ID
       * </pre>
       */
      public Builder setProductId(int value) {
        bitField0_ |= 0x00000002;
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 product_id = 2;</code>
       *
       * <pre>
       * USB product ID
       * </pre>
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        productId_ = 0;
        onChanged();
        return this;
      }

      // optional string serial_number = 3;
      private java.lang.Object serialNumber_ = "";
      /**
       * <code>optional string serial_number = 3;</code>
       *
       * <pre>
       * USB serial number
       * </pre>
       */
      public boolean hasSerialNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string serial_number = 3;</code>
       *
       * <pre>
       * USB serial number
       * </pre>
       */
      public java.lang.String getSerialNumber() {
        java.lang.Object ref = serialNumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serialNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serial_number = 3;</code>
       *
       * <pre>
       * USB serial number
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSerialNumberBytes() {
        java.lang.Object ref = serialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serial_number = 3;</code>
       *
       * <pre>
       * USB serial number
       * </pre>
       */
      public Builder setSerialNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serial_number = 3;</code>
       *
       * <pre>
       * USB serial number
       * </pre>
       */
      public Builder clearSerialNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serialNumber_ = getDefaultInstance().getSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serial_number = 3;</code>
       *
       * <pre>
       * USB serial number
       * </pre>
       */
      public Builder setSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serialNumber_ = value;
        onChanged();
        return this;
      }

      // optional string path = 4;
      private java.lang.Object path_ = "";
      /**
       * <code>optional string path = 4;</code>
       *
       * <pre>
       * USB device path
       * </pre>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string path = 4;</code>
       *
       * <pre>
       * USB device path
       * </pre>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string path = 4;</code>
       *
       * <pre>
       * USB device path
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string path = 4;</code>
       *
       * <pre>
       * USB device path
       * </pre>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 4;</code>
       *
       * <pre>
       * USB device path
       * </pre>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000008);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 4;</code>
       *
       * <pre>
       * USB device path
       * </pre>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DeviceDescriptor)
    }

    static {
      defaultInstance = new DeviceDescriptor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeviceDescriptor)
  }

  public interface ConfigurationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string whitelist_urls = 1;
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    java.util.List<java.lang.String>
    getWhitelistUrlsList();
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    int getWhitelistUrlsCount();
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    java.lang.String getWhitelistUrls(int index);
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    com.google.protobuf.ByteString
        getWhitelistUrlsBytes(int index);

    // repeated string blacklist_urls = 2;
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    java.util.List<java.lang.String>
    getBlacklistUrlsList();
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    int getBlacklistUrlsCount();
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    java.lang.String getBlacklistUrls(int index);
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    com.google.protobuf.ByteString
        getBlacklistUrlsBytes(int index);

    // required .google.protobuf.FileDescriptorSet wire_protocol = 3;
    /**
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     *
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     */
    boolean hasWireProtocol();
    /**
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     *
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSet getWireProtocol();
    /**
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     *
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getWireProtocolOrBuilder();

    // repeated .DeviceDescriptor known_devices = 4;
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    java.util.List<Config.DeviceDescriptor> 
        getKnownDevicesList();
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    Config.DeviceDescriptor getKnownDevices(int index);
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    int getKnownDevicesCount();
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    java.util.List<? extends Config.DeviceDescriptorOrBuilder> 
        getKnownDevicesOrBuilderList();
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    Config.DeviceDescriptorOrBuilder getKnownDevicesOrBuilder(
        int index);

    // optional uint32 valid_until = 5;
    /**
     * <code>optional uint32 valid_until = 5;</code>
     *
     * <pre>
     * expiration timestamp
     * </pre>
     */
    boolean hasValidUntil();
    /**
     * <code>optional uint32 valid_until = 5;</code>
     *
     * <pre>
     * expiration timestamp
     * </pre>
     */
    int getValidUntil();
  }
  /**
   * Protobuf type {@code Configuration}
   *
   * <pre>
   **
   * Plugin Configuration
   * </pre>
   */
  public static final class Configuration extends
      com.google.protobuf.GeneratedMessage
      implements ConfigurationOrBuilder {
    // Use Configuration.newBuilder() to construct.
    private Configuration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Configuration(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Configuration defaultInstance;
    public static Configuration getDefaultInstance() {
      return defaultInstance;
    }

    public Configuration getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Configuration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                whitelistUrls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              whitelistUrls_.add(input.readBytes());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                blacklistUrls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              blacklistUrls_.add(input.readBytes());
              break;
            }
            case 26: {
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = wireProtocol_.toBuilder();
              }
              wireProtocol_ = input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorSet.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wireProtocol_);
                wireProtocol_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                knownDevices_ = new java.util.ArrayList<Config.DeviceDescriptor>();
                mutable_bitField0_ |= 0x00000008;
              }
              knownDevices_.add(input.readMessage(Config.DeviceDescriptor.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              validUntil_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          whitelistUrls_ = new com.google.protobuf.UnmodifiableLazyStringList(whitelistUrls_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          blacklistUrls_ = new com.google.protobuf.UnmodifiableLazyStringList(blacklistUrls_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          knownDevices_ = java.util.Collections.unmodifiableList(knownDevices_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Config.internal_static_Configuration_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Config.internal_static_Configuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Config.Configuration.class, Config.Configuration.Builder.class);
    }

    public static com.google.protobuf.Parser<Configuration> PARSER =
        new com.google.protobuf.AbstractParser<Configuration>() {
      public Configuration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Configuration(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Configuration> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated string whitelist_urls = 1;
    public static final int WHITELIST_URLS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList whitelistUrls_;
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    public java.util.List<java.lang.String>
        getWhitelistUrlsList() {
      return whitelistUrls_;
    }
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    public int getWhitelistUrlsCount() {
      return whitelistUrls_.size();
    }
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    public java.lang.String getWhitelistUrls(int index) {
      return whitelistUrls_.get(index);
    }
    /**
     * <code>repeated string whitelist_urls = 1;</code>
     *
     * <pre>
     * allowed URLs for plugin
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWhitelistUrlsBytes(int index) {
      return whitelistUrls_.getByteString(index);
    }

    // repeated string blacklist_urls = 2;
    public static final int BLACKLIST_URLS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList blacklistUrls_;
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    public java.util.List<java.lang.String>
        getBlacklistUrlsList() {
      return blacklistUrls_;
    }
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    public int getBlacklistUrlsCount() {
      return blacklistUrls_.size();
    }
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    public java.lang.String getBlacklistUrls(int index) {
      return blacklistUrls_.get(index);
    }
    /**
     * <code>repeated string blacklist_urls = 2;</code>
     *
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBlacklistUrlsBytes(int index) {
      return blacklistUrls_.getByteString(index);
    }

    // required .google.protobuf.FileDescriptorSet wire_protocol = 3;
    public static final int WIRE_PROTOCOL_FIELD_NUMBER = 3;
    private com.google.protobuf.DescriptorProtos.FileDescriptorSet wireProtocol_;
    /**
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     *
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     */
    public boolean hasWireProtocol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     *
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSet getWireProtocol() {
      return wireProtocol_;
    }
    /**
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     *
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getWireProtocolOrBuilder() {
      return wireProtocol_;
    }

    // repeated .DeviceDescriptor known_devices = 4;
    public static final int KNOWN_DEVICES_FIELD_NUMBER = 4;
    private java.util.List<Config.DeviceDescriptor> knownDevices_;
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    public java.util.List<Config.DeviceDescriptor> getKnownDevicesList() {
      return knownDevices_;
    }
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    public java.util.List<? extends Config.DeviceDescriptorOrBuilder> 
        getKnownDevicesOrBuilderList() {
      return knownDevices_;
    }
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    public int getKnownDevicesCount() {
      return knownDevices_.size();
    }
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    public Config.DeviceDescriptor getKnownDevices(int index) {
      return knownDevices_.get(index);
    }
    /**
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     *
     * <pre>
     * descriptors of allowed devices
     * </pre>
     */
    public Config.DeviceDescriptorOrBuilder getKnownDevicesOrBuilder(
        int index) {
      return knownDevices_.get(index);
    }

    // optional uint32 valid_until = 5;
    public static final int VALID_UNTIL_FIELD_NUMBER = 5;
    private int validUntil_;
    /**
     * <code>optional uint32 valid_until = 5;</code>
     *
     * <pre>
     * expiration timestamp
     * </pre>
     */
    public boolean hasValidUntil() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 valid_until = 5;</code>
     *
     * <pre>
     * expiration timestamp
     * </pre>
     */
    public int getValidUntil() {
      return validUntil_;
    }

    private void initFields() {
      whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      wireProtocol_ = com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance();
      knownDevices_ = java.util.Collections.emptyList();
      validUntil_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWireProtocol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getWireProtocol().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < whitelistUrls_.size(); i++) {
        output.writeBytes(1, whitelistUrls_.getByteString(i));
      }
      for (int i = 0; i < blacklistUrls_.size(); i++) {
        output.writeBytes(2, blacklistUrls_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(3, wireProtocol_);
      }
      for (int i = 0; i < knownDevices_.size(); i++) {
        output.writeMessage(4, knownDevices_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(5, validUntil_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < whitelistUrls_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(whitelistUrls_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getWhitelistUrlsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blacklistUrls_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(blacklistUrls_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBlacklistUrlsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, wireProtocol_);
      }
      for (int i = 0; i < knownDevices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, knownDevices_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, validUntil_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Config.Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Config.Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Config.Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Config.Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Config.Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Config.Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Config.Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Config.Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Config.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Config.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Config.Configuration prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Configuration}
     *
     * <pre>
     **
     * Plugin Configuration
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Config.ConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Config.internal_static_Configuration_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Config.internal_static_Configuration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Config.Configuration.class, Config.Configuration.Builder.class);
      }

      // Construct using Config.Configuration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWireProtocolFieldBuilder();
          getKnownDevicesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (wireProtocolBuilder_ == null) {
          wireProtocol_ = com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance();
        } else {
          wireProtocolBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (knownDevicesBuilder_ == null) {
          knownDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          knownDevicesBuilder_.clear();
        }
        validUntil_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Config.internal_static_Configuration_descriptor;
      }

      public Config.Configuration getDefaultInstanceForType() {
        return Config.Configuration.getDefaultInstance();
      }

      public Config.Configuration build() {
        Config.Configuration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Config.Configuration buildPartial() {
        Config.Configuration result = new Config.Configuration(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          whitelistUrls_ = new com.google.protobuf.UnmodifiableLazyStringList(
              whitelistUrls_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.whitelistUrls_ = whitelistUrls_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          blacklistUrls_ = new com.google.protobuf.UnmodifiableLazyStringList(
              blacklistUrls_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.blacklistUrls_ = blacklistUrls_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        if (wireProtocolBuilder_ == null) {
          result.wireProtocol_ = wireProtocol_;
        } else {
          result.wireProtocol_ = wireProtocolBuilder_.build();
        }
        if (knownDevicesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            knownDevices_ = java.util.Collections.unmodifiableList(knownDevices_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.knownDevices_ = knownDevices_;
        } else {
          result.knownDevices_ = knownDevicesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000002;
        }
        result.validUntil_ = validUntil_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Config.Configuration) {
          return mergeFrom((Config.Configuration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Config.Configuration other) {
        if (other == Config.Configuration.getDefaultInstance()) return this;
        if (!other.whitelistUrls_.isEmpty()) {
          if (whitelistUrls_.isEmpty()) {
            whitelistUrls_ = other.whitelistUrls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWhitelistUrlsIsMutable();
            whitelistUrls_.addAll(other.whitelistUrls_);
          }
          onChanged();
        }
        if (!other.blacklistUrls_.isEmpty()) {
          if (blacklistUrls_.isEmpty()) {
            blacklistUrls_ = other.blacklistUrls_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBlacklistUrlsIsMutable();
            blacklistUrls_.addAll(other.blacklistUrls_);
          }
          onChanged();
        }
        if (other.hasWireProtocol()) {
          mergeWireProtocol(other.getWireProtocol());
        }
        if (knownDevicesBuilder_ == null) {
          if (!other.knownDevices_.isEmpty()) {
            if (knownDevices_.isEmpty()) {
              knownDevices_ = other.knownDevices_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureKnownDevicesIsMutable();
              knownDevices_.addAll(other.knownDevices_);
            }
            onChanged();
          }
        } else {
          if (!other.knownDevices_.isEmpty()) {
            if (knownDevicesBuilder_.isEmpty()) {
              knownDevicesBuilder_.dispose();
              knownDevicesBuilder_ = null;
              knownDevices_ = other.knownDevices_;
              bitField0_ = (bitField0_ & ~0x00000008);
              knownDevicesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKnownDevicesFieldBuilder() : null;
            } else {
              knownDevicesBuilder_.addAllMessages(other.knownDevices_);
            }
          }
        }
        if (other.hasValidUntil()) {
          setValidUntil(other.getValidUntil());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWireProtocol()) {
          
          return false;
        }
        if (!getWireProtocol().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Config.Configuration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Config.Configuration) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string whitelist_urls = 1;
      private com.google.protobuf.LazyStringList whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureWhitelistUrlsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          whitelistUrls_ = new com.google.protobuf.LazyStringArrayList(whitelistUrls_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public java.util.List<java.lang.String>
          getWhitelistUrlsList() {
        return java.util.Collections.unmodifiableList(whitelistUrls_);
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public int getWhitelistUrlsCount() {
        return whitelistUrls_.size();
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public java.lang.String getWhitelistUrls(int index) {
        return whitelistUrls_.get(index);
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWhitelistUrlsBytes(int index) {
        return whitelistUrls_.getByteString(index);
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public Builder setWhitelistUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWhitelistUrlsIsMutable();
        whitelistUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public Builder addWhitelistUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWhitelistUrlsIsMutable();
        whitelistUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public Builder addAllWhitelistUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureWhitelistUrlsIsMutable();
        super.addAll(values, whitelistUrls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public Builder clearWhitelistUrls() {
        whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string whitelist_urls = 1;</code>
       *
       * <pre>
       * allowed URLs for plugin
       * </pre>
       */
      public Builder addWhitelistUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWhitelistUrlsIsMutable();
        whitelistUrls_.add(value);
        onChanged();
        return this;
      }

      // repeated string blacklist_urls = 2;
      private com.google.protobuf.LazyStringList blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBlacklistUrlsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          blacklistUrls_ = new com.google.protobuf.LazyStringArrayList(blacklistUrls_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public java.util.List<java.lang.String>
          getBlacklistUrlsList() {
        return java.util.Collections.unmodifiableList(blacklistUrls_);
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public int getBlacklistUrlsCount() {
        return blacklistUrls_.size();
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public java.lang.String getBlacklistUrls(int index) {
        return blacklistUrls_.get(index);
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBlacklistUrlsBytes(int index) {
        return blacklistUrls_.getByteString(index);
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public Builder setBlacklistUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlacklistUrlsIsMutable();
        blacklistUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public Builder addBlacklistUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlacklistUrlsIsMutable();
        blacklistUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public Builder addAllBlacklistUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureBlacklistUrlsIsMutable();
        super.addAll(values, blacklistUrls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public Builder clearBlacklistUrls() {
        blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string blacklist_urls = 2;</code>
       *
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       */
      public Builder addBlacklistUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlacklistUrlsIsMutable();
        blacklistUrls_.add(value);
        onChanged();
        return this;
      }

      // required .google.protobuf.FileDescriptorSet wire_protocol = 3;
      private com.google.protobuf.DescriptorProtos.FileDescriptorSet wireProtocol_ = com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> wireProtocolBuilder_;
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public boolean hasWireProtocol() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet getWireProtocol() {
        if (wireProtocolBuilder_ == null) {
          return wireProtocol_;
        } else {
          return wireProtocolBuilder_.getMessage();
        }
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public Builder setWireProtocol(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (wireProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wireProtocol_ = value;
          onChanged();
        } else {
          wireProtocolBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public Builder setWireProtocol(
          com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder builderForValue) {
        if (wireProtocolBuilder_ == null) {
          wireProtocol_ = builderForValue.build();
          onChanged();
        } else {
          wireProtocolBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public Builder mergeWireProtocol(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (wireProtocolBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              wireProtocol_ != com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance()) {
            wireProtocol_ =
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.newBuilder(wireProtocol_).mergeFrom(value).buildPartial();
          } else {
            wireProtocol_ = value;
          }
          onChanged();
        } else {
          wireProtocolBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public Builder clearWireProtocol() {
        if (wireProtocolBuilder_ == null) {
          wireProtocol_ = com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance();
          onChanged();
        } else {
          wireProtocolBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder getWireProtocolBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getWireProtocolFieldBuilder().getBuilder();
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getWireProtocolOrBuilder() {
        if (wireProtocolBuilder_ != null) {
          return wireProtocolBuilder_.getMessageOrBuilder();
        } else {
          return wireProtocol_;
        }
      }
      /**
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       *
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> 
          getWireProtocolFieldBuilder() {
        if (wireProtocolBuilder_ == null) {
          wireProtocolBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder>(
                  wireProtocol_,
                  getParentForChildren(),
                  isClean());
          wireProtocol_ = null;
        }
        return wireProtocolBuilder_;
      }

      // repeated .DeviceDescriptor known_devices = 4;
      private java.util.List<Config.DeviceDescriptor> knownDevices_ =
        java.util.Collections.emptyList();
      private void ensureKnownDevicesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          knownDevices_ = new java.util.ArrayList<Config.DeviceDescriptor>(knownDevices_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Config.DeviceDescriptor, Config.DeviceDescriptor.Builder, Config.DeviceDescriptorOrBuilder> knownDevicesBuilder_;

      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public java.util.List<Config.DeviceDescriptor> getKnownDevicesList() {
        if (knownDevicesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(knownDevices_);
        } else {
          return knownDevicesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public int getKnownDevicesCount() {
        if (knownDevicesBuilder_ == null) {
          return knownDevices_.size();
        } else {
          return knownDevicesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Config.DeviceDescriptor getKnownDevices(int index) {
        if (knownDevicesBuilder_ == null) {
          return knownDevices_.get(index);
        } else {
          return knownDevicesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder setKnownDevices(
          int index, Config.DeviceDescriptor value) {
        if (knownDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownDevicesIsMutable();
          knownDevices_.set(index, value);
          onChanged();
        } else {
          knownDevicesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder setKnownDevices(
          int index, Config.DeviceDescriptor.Builder builderForValue) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.set(index, builderForValue.build());
          onChanged();
        } else {
          knownDevicesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder addKnownDevices(Config.DeviceDescriptor value) {
        if (knownDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownDevicesIsMutable();
          knownDevices_.add(value);
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder addKnownDevices(
          int index, Config.DeviceDescriptor value) {
        if (knownDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownDevicesIsMutable();
          knownDevices_.add(index, value);
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder addKnownDevices(
          Config.DeviceDescriptor.Builder builderForValue) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.add(builderForValue.build());
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder addKnownDevices(
          int index, Config.DeviceDescriptor.Builder builderForValue) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.add(index, builderForValue.build());
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder addAllKnownDevices(
          java.lang.Iterable<? extends Config.DeviceDescriptor> values) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          super.addAll(values, knownDevices_);
          onChanged();
        } else {
          knownDevicesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder clearKnownDevices() {
        if (knownDevicesBuilder_ == null) {
          knownDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          knownDevicesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Builder removeKnownDevices(int index) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.remove(index);
          onChanged();
        } else {
          knownDevicesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Config.DeviceDescriptor.Builder getKnownDevicesBuilder(
          int index) {
        return getKnownDevicesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Config.DeviceDescriptorOrBuilder getKnownDevicesOrBuilder(
          int index) {
        if (knownDevicesBuilder_ == null) {
          return knownDevices_.get(index);  } else {
          return knownDevicesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public java.util.List<? extends Config.DeviceDescriptorOrBuilder> 
           getKnownDevicesOrBuilderList() {
        if (knownDevicesBuilder_ != null) {
          return knownDevicesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(knownDevices_);
        }
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Config.DeviceDescriptor.Builder addKnownDevicesBuilder() {
        return getKnownDevicesFieldBuilder().addBuilder(
            Config.DeviceDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public Config.DeviceDescriptor.Builder addKnownDevicesBuilder(
          int index) {
        return getKnownDevicesFieldBuilder().addBuilder(
            index, Config.DeviceDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       *
       * <pre>
       * descriptors of allowed devices
       * </pre>
       */
      public java.util.List<Config.DeviceDescriptor.Builder> 
           getKnownDevicesBuilderList() {
        return getKnownDevicesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Config.DeviceDescriptor, Config.DeviceDescriptor.Builder, Config.DeviceDescriptorOrBuilder> 
          getKnownDevicesFieldBuilder() {
        if (knownDevicesBuilder_ == null) {
          knownDevicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Config.DeviceDescriptor, Config.DeviceDescriptor.Builder, Config.DeviceDescriptorOrBuilder>(
                  knownDevices_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          knownDevices_ = null;
        }
        return knownDevicesBuilder_;
      }

      // optional uint32 valid_until = 5;
      private int validUntil_ ;
      /**
       * <code>optional uint32 valid_until = 5;</code>
       *
       * <pre>
       * expiration timestamp
       * </pre>
       */
      public boolean hasValidUntil() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 valid_until = 5;</code>
       *
       * <pre>
       * expiration timestamp
       * </pre>
       */
      public int getValidUntil() {
        return validUntil_;
      }
      /**
       * <code>optional uint32 valid_until = 5;</code>
       *
       * <pre>
       * expiration timestamp
       * </pre>
       */
      public Builder setValidUntil(int value) {
        bitField0_ |= 0x00000010;
        validUntil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 valid_until = 5;</code>
       *
       * <pre>
       * expiration timestamp
       * </pre>
       */
      public Builder clearValidUntil() {
        bitField0_ = (bitField0_ & ~0x00000010);
        validUntil_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Configuration)
    }

    static {
      defaultInstance = new Configuration(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Configuration)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceDescriptor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeviceDescriptor_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Configuration_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Configuration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\032 google/protobuf/descript" +
      "or.proto\"^\n\020DeviceDescriptor\022\021\n\tvendor_i" +
      "d\030\001 \001(\r\022\022\n\nproduct_id\030\002 \001(\r\022\025\n\rserial_nu" +
      "mber\030\003 \001(\t\022\014\n\004path\030\004 \001(\t\"\271\001\n\rConfigurati" +
      "on\022\026\n\016whitelist_urls\030\001 \003(\t\022\026\n\016blacklist_" +
      "urls\030\002 \003(\t\0229\n\rwire_protocol\030\003 \002(\0132\".goog" +
      "le.protobuf.FileDescriptorSet\022(\n\rknown_d" +
      "evices\030\004 \003(\0132\021.DeviceDescriptor\022\023\n\013valid" +
      "_until\030\005 \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DeviceDescriptor_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DeviceDescriptor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DeviceDescriptor_descriptor,
              new java.lang.String[] { "VendorId", "ProductId", "SerialNumber", "Path", });
          internal_static_Configuration_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Configuration_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Configuration_descriptor,
              new java.lang.String[] { "WhitelistUrls", "BlacklistUrls", "WireProtocol", "KnownDevices", "ValidUntil", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
