package org.multibit.hd.hardware.core.fsm;

/**
 * <p>Value object to provide the following to hardware wallet FSM:</p>
 * <ul>
 * <li>Context state for creating a wallet on the device</li>
 * </ul>
 *
 * @since 0.0.1
 */

public class CreateWalletSpecification {

  private final String language;
  private final String label;
  private final boolean displayRandom;
  private final boolean pinProtection;
  private final int strength;

  /**
   * @param language      The language to use (e.g. "english")
   * @param label         The label to display below the logo (e.g "Fred")
   * @param displayRandom True if the device should display the entropy generated by the device before asking for additional entropy
   * @param pinProtection True if the device should use PIN protection
   * @param strength      The bits of entropy in the seed phrase (128, 192, 256) corresponding to 12, 18, 24 words
   */
  public CreateWalletSpecification(
    String language,
    String label,
    boolean displayRandom,
    boolean pinProtection,
    int strength
  ) {
    this.language = language;
    this.label = label;
    this.displayRandom = displayRandom;
    this.pinProtection = pinProtection;
    this.strength = strength;
  }

  /**
   * @return The language to use (e.g. "english")
   */
  public String getLanguage() {
    return language;
  }

  /**
   * @return The label to display below the logo (e.g "Fred")
   */
  public String getLabel() {
    return label;
  }

  /**
   * @return True if the device should display the entropy generated by the device before asking for additional entropy
   */
  public boolean isDisplayRandom() {
    return displayRandom;
  }

  /**
   * @return True if the device should use PIN protection
   */
  public boolean isPinProtection() {
    return pinProtection;
  }

  /**
   * @return The bits of entropy in the seed phrase
   */
  public int getStrength() {
    return strength;
  }
}
